options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: python
    entrypoint: 'python'
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']

  - name: python
    entrypoint: pip
    args: ["install", "-r", "./extractor/requirements.txt", "--user"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'stat_extractor'    
      - '--runtime'
      - 'python312'           
      - '--trigger-http'        
      - '--entry-point'
      - 'extract_stats' 
      - '--region'
      - 'us-central1' 
      - '--memory'
      - '1GB'      
      - '--source'
      - './extractor/'     
      - '--allow-unauthenticated'

timeout: '480s'

